kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: keycloak
  namespace: smartgen
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - sso.smart-nextgen.com
      secretName: keyvault-keycloak
  rules:
    - host: sso.smart-nextgen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
