apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - group.yaml
  - rolebinding-team-edit.yaml
  - rolebinding-wael-view.yaml
  - resourcequota.yaml
  - limitrange.yaml


